install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("httr")
install.packages("readxl")
install.packages("odbc")
install.packages("RMariaDB")
install.packages("rmarkdown")
